### ISSUE TITLE
set-output is deprecated

### ISSUE THREAD

**Issue by quite** [Sorosliu1029/follower-change#6]
Getting these warnings from running this action:

Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by Sorosliu1029** [comment]
Hi quite, I am a bit busy nowadays, but will try to resolve this issue asap. Contribution is also welcome and appreciated.

**Comment by Sorosliu1029** [comment]
Hi quite, this job is finished. Nothing you need to do. Just enjoy!
